---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^docs/swagger.json$
      - id: mixed-line-ending
      - id: check-yaml
      - id: detect-private-key
      - id: check-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  # - repo: local
  #   hooks:
  #     - id: swagger-codegen
  #       name: Swagger Codegen
  #       entry: swag
  #       args:
  #         - init
  #         - -q
  #         - --generalInfo=main.go
  #         - -o=./docs
  #       language: system
  #       pass_filenames: false

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      # - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=30] # TODO: update to 15
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: go.sum
